#!/bin/bash -ex

## requirements
### - brew
### - node

## for android (docker) setting
brew cask install virtualbox
brew cask install vagrant
vagrant up

## appium for ios setting

npm i

# chartage
brew install carthage

# opencv4nodejs
brew install cmake
npm install -g opencv4nodejs

# ffmpeg
sudo mkdir /usr/local/Frameworks
sudo chown $(whoami):admin /usr/local/Frameworks
brew install ffmpeg

# mjpeg-consumer
npm install -g mjpeg-consumer

# applesimutils
brew tap wix/brew
brew install applesimutils

# idb idb-companion
tap facebook/fb
install idb-companion
install fb-idb

brew install --HEAD libimobiledevice
brew install ios-deploy
brew install ios-webkit-debug-proxy

npx appium-doctor --ios
